const Portfolio = [
  {
    id: 1,
    title: "Spotes",
    description: "spotifyAPIを使って、ユーザーのよく聞く曲をみれます！",
    image_url: "/img/spo.jpg",
    link: "https://spoti-quct.onrender.com/spotes",
    md: "/md/last.md",
  },
  {
    id: 2,
    title: "オープンデータチャレンジ",
    description: "東京の公共交通の情報を5分おきに取得しツイートするbotです！",
    image_url: "/img/tokyo.jpeg",
    link: "https://tokyochallenge.odpt.org/2021/award/06.html#iniad3",
    md: "",
  },
  {
    id: 3,
    title: "SumGPT",
    description: "chatGPTを使って会議を要約できるサービスです",
    image_url: "/img/sum.jpeg",
    link: "https://github.com/s1f10210273/SumGPT",
    md: "",
  },
  {
    id: 4,
    title: "Unity Game",
    description: "大学のロッカーをサイトから開錠することができます",
    image_url: "/img/uni.jpeg",
    link: "https://unityroom.com/games/shu_way",
    md: "",
  },
  {
    id: 5,
    title: "INIAD Locker",
    description: "大学のロッカーをサイトから開錠することができます",
    image_url: "/img/locker.jpg",
    link: "https://github.com/s1f10210273/iniad_locker",
    md: "",
  },
  {
    id: 6,
    title: "旧ポートフォリオ",
    description: "HTMLとbootstrapで作り、Github Pagesで公開しています",
    image_url: "/img/port.jpeg",
    link: "https://s1f10210273.github.io/my_portfolio/index.html",
    md: "",
  },
  {
    id: 7,
    title: "ポートフォリオ",
    description: "このサイトです。next.jsで作りました。",
    image_url: "/img/img.jpeg",
    link: "https://portfolio-opal-nine-16.vercel.app/",
    md: "/md/test.md",
  },
];

export default Portfolio;
